#!/bin/bash
sudo useradd minecraft
sudo usermod -aG wheel minecraft
sudo yum install -y java
sudo su - minecraft
wget https://launcher.mojang.com/v1/objects/fe123682e9cb30031eae351764f653500b7396c9/server.jar
java -Xms1024M -Xmx2048M -jar server.jar nogui

