#!/bin/bash
sudo useradd minecraft
echo -e "password\npassword" | sudo passwd minecraft
sudo usermod -aG wheel minecraft
sudo yum install -y java
sudo su - minecraft <<EOF
curl https://launcher.mojang.com/v1/objects/fe123682e9cb30031eae351764f653500b7396c9/server.jar >> server.jar
echo "#By changing the setting below to TRUE you are indicating your agreement to our EULA (https://account.mojang.com/documents/minecraft_eula).
#Tue Sep 04 10:39:52 UTC 2018
eula=true" > eula.txt
EOF
